### ISSUE TITLE
Links for Prototype and Design Specs, Title

### ISSUE THREAD

**Issue by extfoxDusan** [AdobeXD/plugin-samples#15]
First, great work guys! What you did it's amazing!

I am testing API, and i cannot find references for
- Project Name
- Project links for Prototype and Design Specs

We are building a custom private plugin tool for EXTFOX Slack Channel where our UI/UX Team would publish updates.

Cheers,
Dusan, C.E.O

**Comment by kerrishotts** [comment]
Hi @extfoxDusan -- this is a great idea for a feature request. We're taking those here if you'd like to add your request (that way the community can vote on it and help shape our backlog priorities!):

https://forums.adobexdplatform.com/c/api-feedback/feature-requests

**Comment by dkstevekwak** [comment]
Closed the issue - the requests has been forwarded to the forum
