### ISSUE TITLE
Readme incorrect (case)

### ISSUE THREAD

**Issue by vynjo** [AdobeXD/plugin-samples#17]
in the instructions for MacOS:

`git clone git@github.com:AdobeXD/Plugin-Samples.git plugins`

should be 

`git clone https://github.com/AdobeXD/plugin-samples.git`

or something similar ("P" and "S" should be lowercase.

**Comment by dkstevekwak** [comment]
Thanks for reporting this. Fixed in 440282dbee16e3224b81a62454ed607d2c7285d7
