### ISSUE TITLE
Symlink support

### ISSUE THREAD

**Issue by cameronmcefee** [AdobeXD/plugin-samples#2]
@achicu suggested I open an issue for this here. Does not appear to be possible to symlink an individual plugin folder.

<img width="430" alt="screen shot 2018-08-06 at 2 40 11 pm" src="https://user-images.githubusercontent.com/72919/43742489-fb16bf4c-9986-11e8-9c74-349dbe676ded.png">

**Comment by ashryanbeats** [comment]
For the time being, it would be worth checking out `xdpm`'s watch feature:
https://github.com/AdobeXD/xdpm

Closing this, as it isn't an issue with the samples in this repo. We're now tracking API feedback on the developer forums:
https://forums.adobexdplatform.com/c/api-feedback

**Comment by ashryanbeats** [comment]
Moved here:
https://forums.adobexdplatform.com/t/symlink-support/234
