### ISSUE TITLE
Would it be possible to compress image via canvas?

### ISSUE THREAD

**Issue by zaaack** [AdobeXD/plugin-samples#23]
Hello, I'm not sure here is the right place. I'm working on a plugin rely on fast image compression, using pure js is a bit slow,  but can be easily implemented via canvas. I cannot access canvas in AdobeXD's plugin environment, would it be possible to use more dom API like canvas? Thanks.

**Comment by dkstevekwak** [comment]
Hi @zaaack, do you mind joining the [XD developer community](https://forums.adobexdplatform.com) and post the feature request there? Thank you

**Comment by zaaack** [comment]
@dkstevekwak Sure, I have posted in the forums already. https://forums.adobexdplatform.com/t/please-add-fast-image-compress-api-and-api-to-get-document-title-file-name/393
