### ISSUE TITLE
Image Insert

### ISSUE THREAD

**Issue by maxrafat** [AdobeXD/plugin-samples#27]
Can anyone help me how to Insert Image on Artboard using main js file? Also, can I add HTML elements on the artboard?

**Comment by SnchitGrover** [comment]
From where would you get the image?

**Comment by maxrafat** [comment]
@SnchitGrover From develop folder. i have created a folder where I have the image, main js, and manifest file. I want my plug in to insert the image from the folder.

**Comment by dkstevekwak** [comment]
Hi @maxrafat, you can use the [Storage APIs](https://adobexdplatform.com/plugin-docs/reference/uxp/storage-index.html?h=storage) to read the images and insert them using [ImageFill](https://adobexdplatform.com/plugin-docs/reference/ImageFill.html?h=imagefill). You can find examples of these in this repo as well as on [our docs website](https://adobexdplatform.com/plugin-docs/). Also, for inquiries like this, could you join the [community forum](https://forums.adobexdplatform.com) and ask us there? Thank you
