### ISSUE TITLE
Remove unused image assets

### ISSUE THREAD

**Issue by yoshikinoko** [AdobeXD/plugin-samples#32]
e.g., remove `*@2x.png`, `*@3x.png` files from the project

- e2e-adobe-stock/assets
- ui-playground/welcome/pages/assets
- ui-buttons-galore/
- sg-lots-of-rects/images/

Although, keep files in this project. This is the example that explains the plugin manager's behavior (use the _largest_ of the icons listed).
- ui-dialog-variations/

**Comment by peterflynn** [comment]
@yoshikinoko Are you sure it's correct to remove those?  Does UXP not automatically pick up `@2x` images the way a browser does?

**Comment by kerrishotts** [comment]
It does, but iirc in those particular projects, we don’t reference some of the assets at all  — so those can just go away.

**Comment by peterflynn** [comment]
Ah ok -- so this is less about multi-scale assets than it is just about assets that are entirely unused in general.

**Comment by yoshikinoko** [comment]
@peterflynn 
Sorry, updated issue title `Remove unused multi-scaled images` to `Remove unused image assets`

**Comment by dkstevekwak** [comment]
removed the unused images from the assets folder:
080f34232efa7ced9b37529e1b6313f27e76f171
