### ISSUE TITLE
Remove link of internal demo video

### ISSUE THREAD

**Issue by yoshikinoko** [AdobeXD/plugin-samples#33]
https://github.com/AdobeXD/plugin-samples/blob/86bbfa2865bffec2035b33dda3511e0861d8ac7f/sg-fit-to-object/main.js#L17

https://github.com/AdobeXD/plugin-samples/blob/86bbfa2865bffec2035b33dda3511e0861d8ac7f/sg-margin-guides/main.js#L9

Alternatively, can we host these video in public? like cc-files or youtube?

**Comment by dkstevekwak** [comment]
Removed those videos: 757d67a933bc37d301162abfc4070a70a8ba8a40

Thanks for catching hem @yoshikinoko !
