### ISSUE TITLE
React quick start still has shims for setTimeout(), etc.

### ISSUE THREAD

**Issue by peterflynn** [AdobeXD/plugin-samples#43]
https://github.com/AdobeXD/plugin-samples/blob/master/quick-start-react/src/react-shim.js is out of date.

If we update the sample's `minVersion` to 16, we can remove the `setTimeout()` & `clearTimeout()` shims.

If we update min to 18, we can remove the `requestAnimationFrame()` & `cancelAnimationFrame()` shims.

**Comment by dkstevekwak** [comment]
addressed
