### ISSUE TITLE
JavaScript Support for npm packages

### ISSUE THREAD

**Issue by fe-shin** [AdobeXD/plugin-samples#88]
Hey, I was wondering if there is a list of available packages that you can use with adobe xd plugins? I didn't find anything related in the documentation but this line:
XD's plugin sandbox does not include most Node.js APIs, such as unrestricted filesystem access or the ability to spawn external processes. Npm packages **that only depend on the core JavaScript language APIs** can work in XD, but because XD's require() differs (see above), you will likely have to use webpack or rollup in order to generate a single-file bundle first. ([Source](https://adobexdplatform.com/plugin-docs/reference/javascript/javascript-support.html))

**Comment by ashryanbeats** [comment]
Hi @fe-shin, this is something we've discussed doing, but we don't have anything along these lines. We may consider doing this in the future but no plans at the moment. If you discover any that work, please feel free to share!

**Comment by martinjamesf** [comment]
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ash Ryan <notifications@github.com> Date: 8/5/20  12:04  (GMT-06:00) To: AdobeXD/plugin-samples <plugin-samples@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [AdobeXD/plugin-samples] JavaScript Support for npm packages (#88) 
Hi @fe-shin, this is something we've discussed doing, but we don't have anything along these lines. We may consider doing this in the future but no plans at the moment. If you discover any that work, please feel free to share!

**Comment by martinjamesf** [comment]
The 😚.  😅   Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message -------- Date: 8/5/20  12:04  (GMT-06:00)To: AdobeXD/plugin-samples <plugin-samples@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com>.      Subject: Re: [AdobeXD/plugin-samples] JavaScript Support for npm packages (#88) 
Hi @fe-shin, this is something we've discussed doing, but we don't have anything along these lines. We may consider doing this in the future but no plans at the moment. If you discover any that work, please feel free to share!

**Comment by martinjamesf** [comment]
Sent from my Verizon, Samsung Galaxy smRyan's 👕. hone
-------- Original message --------From: Ash Ryan.         <notifications@github.com> Date: 8/5/20  12:04  (GMT-06:00) To: AdobeXD/plugin-samples <plugin-samples@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [AdobeXD/  ,  plugin.  The.      -samples] JavaScript Support for npm. packages (#88) I,    too 8_ and 
Hi @fe-shin, this is something we've discussed doing, but we don't have anything along these lines. We may consider doing this in the future but no plans at the moment. If you discover any that work, please feel free to share!

**Comment by martinjamesf** [comment]
The. 👕🥽,   🚻 The first thing I did Sent from my Verizon, Samsung Galaxy smartphoneThese

**Comment by martinjamesf** [comment]
They were Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ash Ryan yu<notifications@github.com> Date: 8/5/20  12:04  (GMT-06:00) To: AdobeXD/plugin-samples <plugin-samples@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.c 👕 om> Subject: Re: [AdobeXD/plugin-samples] JavaScript Support for npm 👗👔  package. The es (#88) 
Hi @fe-shin, this is something we've discussed doing, but we don't have anything along these lines. We may consider doing this in the future but no plans at the moment. If you discover any that work, please feel free to share!
